title: AI Conference Deadlines # (Maintained by @FinYang)
# email: Fin.Yang@monash.edu
description: Countdowns to SP/ML/DM/IT/Optimization conference deadlines.
author: Fin Yang
author_link: https://yangzhuoranyang.com/

domain: "zhaogroup.netlify.app"
baseurl: ""

twitter_username: YangzhuoranY
twitter_hashtag:
github_username: FinYang
github_repo: ai-deadlines

ga_id: UA-129140417-1

include: ['_pages']
