title: AI Conference Deadlines # (Maintained by @FinYang)
# email: Fin.Yang@monash.edu
description: Countdowns to SP/ML/DM/IT/Optimization conference deadlines. This page is maintained as a fork from aideadlin.es
author: Abhishek Das

domain: "zhaogroup.netlify.app"
baseurl: ""

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: abhshkdz
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-129140417-1

include: ['_pages']
